pipeline:
#  build:
#    image: elixir:1.5.1
#    links:
#      - db
#    commands:
#      - mix local.hex --force
#      - mix deps.get
#      - mix local.rebar --force
#      - sleep 10
#      - mix ecto.create
#      - mix ecto.migrate
#      - mix test
  deploy:
    image: bittorrent/kubectl
    commands:
      - echo $DRONE_COMMIT_SHA
      - echo ${DRONE_COMMIT_SHA}
      - echo ${{DRONE_COMMIT_SHA}}
      - kubectl config set-credentials default --token=$KUBERNETES_TOKEN_DRUNKSHIP
      - echo $KUBERNETES_CERT_DRUNKSHIP | base64 -d > ca.crt
      - kubectl config set-cluster default --server=$KUBERNETES_SERVER_DRUNKSHIP --certificate-authority=ca.crt
      - kubectl config set-context default --cluster=default --user=default
      - kubectl config use-context default
#      - kubectl --namespace drunkship set image deployment/slowmonster-v1 slowmonster=gcr.io/drunkship-159205/github-composit-slowmonster:${DRONE_COMMIT_SHA} --record 
    secrets: [KUBERNETES_SERVER_DRUNKSHIP, KUBERNETES_TOKEN_DRUNKSHIP, KUBERNETES_CERT_DRUNKSHIP]
services:
  db:
    image: postgres:9.6.5
    environment:
      - POSTGRES_PASSWORD=b4o6L6ZSbUBP
