pipeline:
#  build:
#    image: elixir:1.5.1
#    links:
#      - db
#    commands:
#      - mix local.hex --force
#      - mix deps.get
#      - mix local.rebar --force
#      - sleep 10
#      - mix ecto.create
#      - mix ecto.migrate
#      - mix test
  deploy:
    image: google/cloud-sdk
    environment:
      #- CLOUDSDK_CORE_DISABLE_PROMPTS=1
      #- CLOUDSDK_PYTHON_SITEPACKAGES=1
      - CLOUDSDK_COMPUTE_ZONE=us-central1-b
      - CLOUDSDK_CORE_PROJECT=drunkship-159205
    commands:
      - echo $CLOUDSDK_CORE_PROJECT
      - echo $K8S_SERVER
      - echo $GCLOUD_KEY
      - echo $GCLOUD_EMAIL
      - echo $DRONE_COMMIT_SHA
      - echo $GCLOUD_KEY | base64 --decode > gcloud.p12
      - gcloud auth activate-service-account $GCLOUD_EMAIL --key-file gcloud.p12
      - gcloud docker push gcr.io/drunkship-159205/github-composit-slowmonster:$DRONE_COMMIT_SHA > /dev/null

      secrets: [k8s_server, gcloud_key, gcloud_email]
services:
  db:
    image: postgres:9.6.5
    environment:
      - POSTGRES_PASSWORD=b4o6L6ZSbUBP
