pipeline:
#  build:
#    image: elixir:1.5.1
#    links:
#      - db
#    commands:
#      - mix local.hex --force
#      - mix deps.get
#      - mix local.rebar --force
#      - sleep 10
#      - mix ecto.create
#      - mix ecto.migrate
#      - mix test
  deploy:
		gke:
			image: nytimes/drone-gke

			zone: us-central1-b
			cluster: dtest1
			namespace: drunkship
			token: >
				$K8S_TOKEN

			vars:
				image: gcr.io/drunkship-159205/github-composit-slowmonster:$$COMMIT
				app: slowmonster
				env: prod
			secrets:
				api_token: $$K8S_TOKEN
			secrets_base64:
				p12_cert: $$K8S_CERT
    secrets: [k8s_server, k8s_token, k8s_cert, k8s_cluster]
#    image: tpdock/docker-kubectl:v1.1.0
#    commands:
#      - echo $K8S_SERVER
#      - echo $K8S_TOKEN
#      - echo $K8S_CERT
#      - echo $K8S_CLUSTER
#      #- kubectl config set-credentials default --token=$K8S_TOKEN
#      - echo $K8S_CERT | base64 -d > ca.crt
#      #- kubectl config set-cluster default --server=$K8S_SERVER --certificate-authority=ca.crt
#      #- kubectl config set-context default --cluster=default --user=default
#      #- kubectl config use-context default
#      - kubectl --namespace drunkship
#        --token=$K8S_TOKEN
#        --server=$K8S_SERVER
#        --certificate-authority=ca.crt
#        set image deployment/slowmonster-v1 slowmonster=gcr.io/drunkship-159205/github-composit-slowmonster:$DRONE_COMMIT_SHA
services:
  db:
    image: postgres:9.6.5
    environment:
      - POSTGRES_PASSWORD=b4o6L6ZSbUBP
