pipeline:
  build:
    image: elixir:1.5.1
    commands:
      - mix local.hex --force
      - mix deps.get
      - mix local.rebar --force
      - sleep 10
      - mix ecto.create
      - mix ecto.migrate
      - mix test
  deploy:
    image: google/cloud-sdk
    commands:
      - echo $GCLOUD_KEY | base64 --decode > gcloud.p12
      - gcloud auth activate-service-account $GCLOUD_EMAIL --key-file gcloud.p12
      - gcloud container clusters get-credentials $GCLOUD_CLUSTER --zone $GCLOUD_ZONE --project $GCLOUD_PROJECT
      - ssh-keygen -f ~/.ssh/google_compute_engine -N ""
      - kubectl --insecure-skip-tls-verify --namespace $GCLOUD_NAMESPACE set image deployment/$GCLOUD_DEPLOYMENT slowmonster=gcr.io/$GCLOUD_PROJECT/$GCLOUD_IMAGE:$DRONE_COMMIT_SHA
    secrets: [k8s_server, gcloud_key, gcloud_email, gcloud_project, gcloud_image, gcloud_zone, gcloud_cluster, gcloud_namespace, gcloud_deployment]
services:
  db:
    image: postgres:9.6.5
    environment:
      - POSTGRES_PASSWORD=b4o6L6ZSbUBP
